# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20171121_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='related_cases',
            field=models.ManyToManyField(blank=True, null=True, related_name='_case_related_cases_+', to='cases.Case'),
        ),
    ]
