# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20171121_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='binder',
            field=models.ManyToManyField(to='cases.Binder'),
        ),
    ]
