# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20171121_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='suspect',
        ),
        migrations.RemoveField(
            model_name='case',
            name='victim',
        ),
        migrations.AddField(
            model_name='case',
            name='suspects',
            field=models.ManyToManyField(related_name='person_suspect', to='cases.Person'),
        ),
        migrations.AddField(
            model_name='case',
            name='victims',
            field=models.ManyToManyField(related_name='person_victim', to='cases.Person'),
        ),
    ]
